application: track-delay
runtime: python27
api_version: 1
threadsafe: true
version: alpha1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /getData
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"